### ISSUE TITLE
[BUG] Colors are not reset after setup

### ISSUE THREAD

**Issue by Sparkles-Laurel** [m3tozz/NeoCat#12]
### Environment Information:
**Operating System**: Arch Linux on kernel 6.4.11-arch1-1
**Host**: Acer Aspire E5-574G with Insyde H2O v1.18 Firmware
**Terminal Emulator**: kitty 0.29.2
**Terminal Font**: Cascadia Code Powerline (11.0pt)
**Shell**: bash 5.1.16

### Steps to reproduce:
1. Clone neocat repository and change into the cloned directory
2. execute `chmod a+x ./neocat.sh && ./neocat.sh --shell`
3. hit enter when the prompt is displayed
4. Observe

### Expected Behaviour
the colors of the terminal should be reset
### Actual Behaviour
the bash prompt is rendered as bold cyan
![image](https://github.com/m3tozz/NeoCat/assets/69117901/c63399f1-b184-44bd-aa66-0f3f3058fb49)

**Comment by m3tozz** [comment]
The bug will be fixed in the new version (1.2.9)
