### ISSUE TITLE
Icons not loaded

### ISSUE THREAD

**Issue by PrethamMuthappa** [m3tozz/NeoCat#15]
The neocat theme loads successfully except the icons, I followed the instructions and ran the install-icon script , even after that the icon are not loaded for any of the themes 
![image](https://github.com/m3tozz/NeoCat/assets/98420696/488d0f26-237e-4df5-b94c-e0a07f3c0acb)

**Comment by m3tozz** [comment]
Install font- awesome pack https://fontawesome.com/

**Comment by m3tozz** [comment]
try "sudo apt install fonts-font-awesome" command and install a nerd font https://www.nerdfonts.com/font-downloads
